line-length = 100
target-version = "py310"

[lint]
select = [
    "E",
    "F",
    "I",
    "B",
    "UP",
    "ASYNC",
]
ignore = ["B008"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
